POST http://localhost:2023/items
Content-Type: application/json

{
  "name": "Pringles Originals",
  "brand": "Pringles",
  "shop": "Megamarket",
  "acronym": "SBER",
  "country": "Russia"
}
###
PATCH http://localhost:2023/items/655d21c1a7d27d6f4a0a5353
Content-Type: application/json

{
  "price": 200,
  "currency": "rubles"
}

###
POST http://localhost:2023/items
Content-Type: application/json

{
  "name": "Pringles Originals",
  "brand": "Pringles",
  "shop": "Jumbo",
  "acronym": "JMB",
  "country": "The Netherlands"
}

###
PATCH http://localhost:2023/items/655f6744a790687464a168eb
Content-Type: application/json

{
  "price": 1.89,
  "currency": "euro"
}

###
GET http://localhost:2023/items/prices